# $HOME/.config/alacritty/alacritty.toml

# -----------
# Color Theme
# -----------

import = [ "C:/Users/rafal/AppData/Roaming/alacritty/themes/tokyo-night.toml" ] # Windows
# import = [ "~/.config/alacritty/themes/tokyo-night.toml" ]  # Linux

# -----------
# Config
# -----------

live_config_reload = true

[scrolling]
history = 10000     # Default: 10000
multiplier = 3      # Default: 3

[window]
dynamic_title = true

opacity = 1.0

padding.x = 5
padding.y = 5

decorations = "Full"
decorations_theme_variant = "Dark"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Bold" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

size = 9.0

[selection]
save_to_clipboard = true

